#%RAML 1.0 DocumentationItem
title: Demo Process API
content: |
  This API will be used to interact with the fake Population database. As per the requirement for implementation, it will be having one resource to retrieve Population registration details for a given Population registration number. However, this API will/can be extended later to provide more functionality.

 
