#%RAML 1.0 DataType

description: Status of the API with release version.
type: object
properties:
  status:
    type: string
    description: Status of the API.
    example: Running
  version:
    type: string
    description: Release version of the API deployed.
    example: r.master.0001
